### ISSUE TITLE
initial code

### ISSUE THREAD

**Issue by schettino72** [pydoit/doit-watch#1]
https://github.com/pydoit/doit-auto1/pull/1

**Comment by schettino72** [comment]
@bollwyvl if you feel like kickstarting it.
Feel free to commit directly. no need PRs at this stage.

**Comment by bollwyvl** [comment]
Sounds good.

I'll push something later today. Basic plan... Aside from s/auto/watch/ I'd
like to get a basic dodo.py and github workflow working.

**Comment by bollwyvl** [comment]
It looks like we're right back where we were w/r/t `multiprocessing` on osx and windows... probably have to consider another execution approach...

**Comment by schettino72** [comment]
It seems the error on CI is coming from pytest...

Can we simplify the CI to use pytest directly instead of "doit -> pytest + coverage -> doit"?
It makes it very hard to debug problems...

**Comment by schettino72** [comment]
> It looks like we're right back where we were w/r/t multiprocessing on osx and windows... probably have to consider another execution approach...

Any idea what to use?

**Comment by schettino72** [comment]
I will close this issue. initial code is there...
